#!/bin/bash

set -Eeo pipefail

###########################
# Local Config Parameters #
###########################

AWS_DEFAULT_REGION=eu-west-2
export NHS_SERVICE=repo-to-gp

####################################
# Instance (Environment) Variables #
####################################

function check_env {
  if [[ -z "${NHS_ENVIRONMENT}" ]]; then
    echo "Must set NHS_ENVIRONMENT"
    exit 1
  fi
}

function get_aws_account_id {
  AWS_ACCOUNT_ID=$(dojo -c Dojofile-infra "aws sts get-caller-identity | jq -r .Account")
}

function configure_repo_to_gp_service_auth_keys {
  parameter_name="/repo/${NHS_ENVIRONMENT}/user-input/repo-to-gp-authorization-keys"
  echo "${parameter_name}"
  export REPO_TO_GP_AUTHORIZATION_KEYS=$(dojo -c Dojofile-infra "aws ssm get-parameter --with-decryption --region ${AWS_DEFAULT_REGION} --name  ${parameter_name} | jq -r .Parameter.Value")
}

function configure_ehr_repo_service_auth_keys {
  parameter_name="/repo/${NHS_ENVIRONMENT}/user-input/ehr-repo-authorization-keys"
  echo "${parameter_name}"
  export EHR_REPO_AUTHORIZATION_KEYS=$(dojo -c Dojofile-infra "aws ssm get-parameter --with-decryption --region ${AWS_DEFAULT_REGION} --name  ${parameter_name} | jq -r .Parameter.Value")
}

function configure_mhs_inbound_url {
  check_env
  if [[ $NHS_ENVIRONMENT == "dev" ]]; then
    export MHS_INBOUND_URL=http://mhs-inbound-dev-opentest.mhs.patient-deductions.nhs.uk
  else
    export MHS_INBOUND_URL=http://mhs-inbound-test-b86041.mhs.patient-deductions.nhs.uk
  fi
}

###########
## TASKS ##
###########

command="$1"
case "${command}" in
  _test_lint)
      npm install
      npm run lint
      ;;
  test_lint)
      dojo "./tasks _test_lint"
      ;;
  _test_e2e)
      npm install
      npm run test
      ;;
  test_e2e)
      check_env
      get_aws_account_id
      configure_repo_to_gp_service_auth_keys
      configure_ehr_repo_service_auth_keys
      configure_mhs_inbound_url
      dojo "./tasks _test_e2e"
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e